### ISSUE TITLE
Install Redis on Linux

### ISSUE THREAD

**Issue by conservators** [redis/redis-doc#2364] opened 2023-03-23 02:44 UTC
在5.0.5版本中，哨兵通信命令 subscribe _sentinel_:hello 命令时间过长，触发了监控警告，有什么办法排除原因嘛，几台redis服务设备都在一个网段内
![image](https://user-images.githubusercontent.com/34743247/227086242-5b0f5fa5-0521-4170-a99b-9da92194eb4d.png)

**Comment by itamarhaber** [comment] 2023-03-23 10:52
Hello @conservators,

Please use English to report the issue.

**Comment by nermiller** [comment] 2023-03-30 20:43
@itamarhaber, translated it says, "In version 5.0.5, the sentinel communication command subscribe sentinel:hello command takes too long and triggers a monitoring warning. Is there any way to eliminate the cause? Several redis service devices are in the same network segment.

**Comment by mich-elle-luna** [comment] 2023-12-26 22:01
not a doc issue, closing

**Closed by mich-elle-luna** 2023-12-26 22:01 UTC
