### ISSUE TITLE
Scaling with Redis Cluster - cluster-slave-validity-factor

### ISSUE THREAD

**Issue by Qualatea** [redis/redis-doc#2445] opened 2023-06-22 11:11 UTC
There might be just a slight misclick. The documentation specifies "cluster-slave-validity-factor" but the config file calls it "cluster-replica-validity-factor". 
To be precise it's here :
https://redis.io/docs/management/scaling/

**Comment by zuiderkwast** [comment] 2023-09-06 22:56
Many configs with slave in the name got aliases added with the word replica instead. Both work but we should use "replica" in the docs. Feel free to post a PR.

**Comment by mich-elle-luna** [comment] 2023-12-26 22:37
duplicate of #2353, closing

**Closed by mich-elle-luna** 2023-12-26 22:37 UTC
